// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth_sdk/protobuf/client_list_control_pb2/client_list_control.proto

/*
Package client_list_control_pb2 is a generated protocol buffer package.

It is generated from these files:
	sawtooth_sdk/protobuf/client_list_control_pb2/client_list_control.proto

It has these top-level messages:
	ClientPagingControls
	ClientPagingResponse
	ClientSortControls
*/
package client_list_control_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Paging controls to be sent with List requests.
// Attributes:
//     start_id: The id of a resource to start the page with
//     end_id: The id of a resource to end the page with
//     min_index: A resource index relative to the query, the newest being 0
//     count: The number of results per page, defaults to and maxes out at 1000
type ClientPagingControls struct {
	// Types that are valid to be assigned to LocationMarker:
	//	*ClientPagingControls_StartId
	//	*ClientPagingControls_EndId
	//	*ClientPagingControls_StartIndex
	LocationMarker isClientPagingControls_LocationMarker `protobuf_oneof:"location_marker"`
	Count          int32                                 `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
}

func (m *ClientPagingControls) Reset()                    { *m = ClientPagingControls{} }
func (m *ClientPagingControls) String() string            { return proto.CompactTextString(m) }
func (*ClientPagingControls) ProtoMessage()               {}
func (*ClientPagingControls) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isClientPagingControls_LocationMarker interface {
	isClientPagingControls_LocationMarker()
}

type ClientPagingControls_StartId struct {
	StartId string `protobuf:"bytes,1,opt,name=start_id,json=startId,oneof"`
}
type ClientPagingControls_EndId struct {
	EndId string `protobuf:"bytes,2,opt,name=end_id,json=endId,oneof"`
}
type ClientPagingControls_StartIndex struct {
	StartIndex int32 `protobuf:"varint,3,opt,name=start_index,json=startIndex,oneof"`
}

func (*ClientPagingControls_StartId) isClientPagingControls_LocationMarker()    {}
func (*ClientPagingControls_EndId) isClientPagingControls_LocationMarker()      {}
func (*ClientPagingControls_StartIndex) isClientPagingControls_LocationMarker() {}

func (m *ClientPagingControls) GetLocationMarker() isClientPagingControls_LocationMarker {
	if m != nil {
		return m.LocationMarker
	}
	return nil
}

func (m *ClientPagingControls) GetStartId() string {
	if x, ok := m.GetLocationMarker().(*ClientPagingControls_StartId); ok {
		return x.StartId
	}
	return ""
}

func (m *ClientPagingControls) GetEndId() string {
	if x, ok := m.GetLocationMarker().(*ClientPagingControls_EndId); ok {
		return x.EndId
	}
	return ""
}

func (m *ClientPagingControls) GetStartIndex() int32 {
	if x, ok := m.GetLocationMarker().(*ClientPagingControls_StartIndex); ok {
		return x.StartIndex
	}
	return 0
}

func (m *ClientPagingControls) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientPagingControls) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientPagingControls_OneofMarshaler, _ClientPagingControls_OneofUnmarshaler, _ClientPagingControls_OneofSizer, []interface{}{
		(*ClientPagingControls_StartId)(nil),
		(*ClientPagingControls_EndId)(nil),
		(*ClientPagingControls_StartIndex)(nil),
	}
}

func _ClientPagingControls_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientPagingControls)
	// location_marker
	switch x := m.LocationMarker.(type) {
	case *ClientPagingControls_StartId:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StartId)
	case *ClientPagingControls_EndId:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.EndId)
	case *ClientPagingControls_StartIndex:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.StartIndex))
	case nil:
	default:
		return fmt.Errorf("ClientPagingControls.LocationMarker has unexpected type %T", x)
	}
	return nil
}

func _ClientPagingControls_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientPagingControls)
	switch tag {
	case 1: // location_marker.start_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.LocationMarker = &ClientPagingControls_StartId{x}
		return true, err
	case 2: // location_marker.end_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.LocationMarker = &ClientPagingControls_EndId{x}
		return true, err
	case 3: // location_marker.start_index
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.LocationMarker = &ClientPagingControls_StartIndex{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _ClientPagingControls_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientPagingControls)
	// location_marker
	switch x := m.LocationMarker.(type) {
	case *ClientPagingControls_StartId:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StartId)))
		n += len(x.StartId)
	case *ClientPagingControls_EndId:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.EndId)))
		n += len(x.EndId)
	case *ClientPagingControls_StartIndex:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.StartIndex))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Information about the pagination used, sent back with List responses.
// Attributes:
//     next_id: The id of the first resource in the next page
//     previous_id: The id of the last resource in the previous page
//     start_index: The index of the first resource in this page
//     total_resources: The total resources available from the requested query
type ClientPagingResponse struct {
	NextId         string `protobuf:"bytes,1,opt,name=next_id,json=nextId" json:"next_id,omitempty"`
	PreviousId     string `protobuf:"bytes,2,opt,name=previous_id,json=previousId" json:"previous_id,omitempty"`
	StartIndex     int32  `protobuf:"varint,3,opt,name=start_index,json=startIndex" json:"start_index,omitempty"`
	TotalResources int32  `protobuf:"varint,4,opt,name=total_resources,json=totalResources" json:"total_resources,omitempty"`
}

func (m *ClientPagingResponse) Reset()                    { *m = ClientPagingResponse{} }
func (m *ClientPagingResponse) String() string            { return proto.CompactTextString(m) }
func (*ClientPagingResponse) ProtoMessage()               {}
func (*ClientPagingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientPagingResponse) GetNextId() string {
	if m != nil {
		return m.NextId
	}
	return ""
}

func (m *ClientPagingResponse) GetPreviousId() string {
	if m != nil {
		return m.PreviousId
	}
	return ""
}

func (m *ClientPagingResponse) GetStartIndex() int32 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

func (m *ClientPagingResponse) GetTotalResources() int32 {
	if m != nil {
		return m.TotalResources
	}
	return 0
}

// Sorting controls to be sent with List requests. More than one can be sent.
// If so, the first is used, and additional controls are tie-breakers.
// Attributes:
//     keys: Nested set of keys to sort by (i.e. ['header', 'signer_public_key'])
//     reverse: Whether or not to reverse the sort (i.e. descending order)
//     compare_length: Sorts by value length, rather than the property itself
type ClientSortControls struct {
	Keys          []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Reverse       bool     `protobuf:"varint,2,opt,name=reverse" json:"reverse,omitempty"`
	CompareLength bool     `protobuf:"varint,3,opt,name=compare_length,json=compareLength" json:"compare_length,omitempty"`
}

func (m *ClientSortControls) Reset()                    { *m = ClientSortControls{} }
func (m *ClientSortControls) String() string            { return proto.CompactTextString(m) }
func (*ClientSortControls) ProtoMessage()               {}
func (*ClientSortControls) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClientSortControls) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ClientSortControls) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

func (m *ClientSortControls) GetCompareLength() bool {
	if m != nil {
		return m.CompareLength
	}
	return false
}

func init() {
	proto.RegisterType((*ClientPagingControls)(nil), "ClientPagingControls")
	proto.RegisterType((*ClientPagingResponse)(nil), "ClientPagingResponse")
	proto.RegisterType((*ClientSortControls)(nil), "ClientSortControls")
}

func init() {
	proto.RegisterFile("sawtooth_sdk/protobuf/client_list_control_pb2/client_list_control.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xcb, 0x4e, 0xe3, 0x40,
	0x10, 0x45, 0xc7, 0x93, 0xe7, 0x54, 0x34, 0x89, 0xc6, 0xca, 0x28, 0x96, 0x58, 0x00, 0x91, 0x10,
	0xac, 0x12, 0x29, 0xfc, 0x41, 0xb2, 0x00, 0x24, 0x16, 0x51, 0xb3, 0x63, 0xd3, 0x72, 0xec, 0x22,
	0xb1, 0xe2, 0x74, 0x59, 0xdd, 0x65, 0x08, 0x7f, 0x82, 0xf8, 0x5a, 0xda, 0x6d, 0x3b, 0x88, 0xd7,
	0xce, 0x75, 0x4f, 0x97, 0xea, 0xc8, 0x17, 0xae, 0x4c, 0xf8, 0xc4, 0x44, 0xbc, 0x91, 0x26, 0xde,
	0x4e, 0x33, 0x4d, 0x4c, 0xab, 0xfc, 0x61, 0x1a, 0xa5, 0x09, 0x2a, 0x96, 0x69, 0x62, 0x58, 0x46,
	0xa4, 0x58, 0x53, 0x2a, 0xb3, 0xd5, 0xec, 0xbb, 0x7c, 0xe2, 0x96, 0xc6, 0x2f, 0x1e, 0x0c, 0x17,
	0x8e, 0x2e, 0xc3, 0x75, 0xa2, 0xd6, 0x8b, 0x92, 0x1a, 0xff, 0x08, 0xba, 0x86, 0x43, 0xcd, 0x32,
	0x89, 0x03, 0xef, 0xc4, 0xbb, 0xf8, 0x73, 0xfd, 0x4b, 0x74, 0x5c, 0x72, 0x13, 0xfb, 0x23, 0x68,
	0xa3, 0x8a, 0x0b, 0xf4, 0xbb, 0x42, 0x2d, 0x3b, 0x5b, 0x70, 0x0a, 0xbd, 0x6a, 0x4b, 0xc5, 0xb8,
	0x0f, 0x1a, 0x96, 0xb6, 0x2c, 0x85, 0x72, 0xb1, 0xc8, 0xfc, 0x21, 0xb4, 0x22, 0xca, 0x15, 0x07,
	0xcd, 0x02, 0x8a, 0x72, 0x98, 0xff, 0x83, 0x41, 0x4a, 0x51, 0xc8, 0x09, 0x29, 0xb9, 0x0b, 0xf5,
	0x16, 0xf5, 0xf8, 0xf5, 0x93, 0x9a, 0x40, 0x93, 0x91, 0x32, 0x68, 0xaf, 0x77, 0x14, 0xee, 0xdf,
	0xcd, 0x44, 0xbb, 0x18, 0xed, 0xf5, 0x63, 0xe8, 0x65, 0x1a, 0x1f, 0x13, 0xca, 0xcd, 0xc1, 0x4d,
	0x40, 0x1d, 0x95, 0x0f, 0xbe, 0xe8, 0x7d, 0x90, 0x3b, 0x87, 0x01, 0x13, 0x87, 0xa9, 0xd4, 0x68,
	0x28, 0xd7, 0x11, 0x9a, 0x4a, 0xb3, 0xef, 0x62, 0x51, 0xa7, 0xe3, 0x04, 0xfc, 0xd2, 0xed, 0x8e,
	0x34, 0x1f, 0x7e, 0x9a, 0x0f, 0xcd, 0x2d, 0x3e, 0x1b, 0xab, 0xd5, 0xb0, 0x97, 0xdd, 0xb7, 0x1f,
	0x40, 0xc7, 0x0a, 0xa0, 0x36, 0xe8, 0x84, 0xba, 0xa2, 0x1e, 0xfd, 0x33, 0xe8, 0x47, 0xb4, 0xcb,
	0x42, 0x8d, 0x32, 0x45, 0xb5, 0xe6, 0x8d, 0x13, 0xea, 0x8a, 0xbf, 0x55, 0x7a, 0xeb, 0xc2, 0xf9,
	0x0c, 0xfe, 0xd7, 0x6d, 0x4f, 0x6c, 0xdb, 0x93, 0xba, 0xed, 0xa5, 0x77, 0x3f, 0xfa, 0xa1, 0xf0,
	0x55, 0xdb, 0x3d, 0xba, 0x7c, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xea, 0x06, 0x94, 0x73, 0x28, 0x02,
	0x00, 0x00,
}
